#This file is developed by Team 25 of COMP90024 of The University of Melbourne.
#Team member - id:
#Xi Chen           983241
#Fangfei Zheng     966172
#Haoran Zhang      960374
#Pengnan Zhao      883338
#Jiangjiahui Lu    965378

---
# Common vars
availability_zone: melbourne-qh2-uom

#Volume
volumes:
  -vol_name: instance_0_vol
   vol_size: 30
  -vol_name: instance_1_vol
   vol_size: 30
  -vol_name: instance_2_vol
   vol_size: 30
  -vol_name: demo-03-vol-2
   vol_size: 10

#Security group
security_groups:
  - name: demo_ssh
    description: "security group for SSH access"
    protocol: tcp
    port_range_min: 22
    port_range_max: 22
    remote_ip_prefix: 0.0.0.0/0
  - name: demo_http
    description: "security group for HTTP"
    protocol: tcp
    port_range_min: 80
    port_range_max: 80
    remote_ip_prefix: 0.0.0.0/0
  - name: couchdb
    description: "security group for couchdb"
    protocol: tcp
    port_range_min: 9100
    port_range_max: 9200
    remote_ip_prefix: 0.0.0.0/0
  - name: 4396
    description: "security group for couchdb cluster setup"
    protocol: tcp
    port_range_min: 4396
    port_range_max: 4396
    remote_ip_prefix: 0.0.0.0/0
   - name: 5984
    description: "security group for couchdb cluster setup"
    protocol: tcp
    port_range_min: 5984
    port_range_max: 5984
    remote_ip_prefix: 0.0.0.0/0
  - name: 5986
    description: "security group for couchdb cluster setup"
    protocol: tcp
    port_range_min: 5986
    port_range_max: 5986
    remote_ip_prefix: 0.0.0.0/0

# instance 
instances:
  - name: instance_0
    volumes: ['instance_0_vol']
  - name: instance_1
    volumes: ['instance_1_vol']
  - name: instance_2
    volumes: ['instance_2_vol']
  - name: instance_3
    volumes: ['demo-03-vol-2']

instance_image: 215f9775-483c-4e0a-b703-d21a5c966f2e
instance_key_name: Group25
instance_flavor: uom.mse.2c9g

#couchdb username and password
username: admin
password: 12345

...
