#This file is developed by Team 25 of COMP90024 of The University of Melbourne.
#Team member - id:
#Xi Chen           983241
#Fangfei Zheng     966172
#Haoran Zhang      960374
#Pengnan Zhao      883338
#Jiangjiahui Lu    965378

---
- name: upload the subnode script
  become: yes
  copy:
    src: ./subnode2.sh
    dest: /home/ubuntu/
    mode: 0777

- name: execute the subnode script
  become: yes
  shell: /home/ubuntu/subnode2.sh

...
