#This file is developed by Team 25 of COMP90024 of The University of Melbourne.
#Team member - id:
#Xi Chen           983241
#Fangfei Zheng     966172
#Haoran Zhang      960374
#Pengnan Zhao      883338
#Jiangjiahui Lu    965378
---
# upload the script and set the remote host to a masternode
- name: upload the masternode script
  become: yes
  copy:
    src: ./masternode.sh
    dest: /home/ubuntu/
    mode: 0777

- name: execute the masternode script
  become: yes
  shell: /home/ubuntu/masternode.sh

...
