default_city = {
    "Darwin" : -1,
    "Palmerston" : -1,
    "Brisbane" : -1,
    "Bundaberg" : -1,
    "Caboolture" : -1,
    "Cairns" : -1,
    "Caloundra" : -1,
    "Gladstone" : -1,
    "Gold Coast" : -1,
    "Gympie" : -1,
    "Hervey Bay" : -1,
    "Ipswich" : -1,
    "Logan" : -1,
    "Mackay" : -1,
    "Maryborough" : -1,
    "Mount Isa" : -1,
    "Rockhampton" : -1,
    "Sunshine Coast" : -1,
    "Toowoomba" : -1,
    "Townsville" : -1,
    "Adelaide" : -1,
    "Mount BarkerMount" : -1,
    "Gambier" : -1,
    "Murray Bridge" : -1,
    "Port Adelaide" : -1,
    "Port Augusta" : -1,
    "Port Pirie" : -1,
    "Port Lincoln" : -1,
    "Victor Harbor" : -1,
    "Whyalla" : -1,
    "Hobart" : -1,
    "Burnie" : -1,
    "Devonport" : -1,
    "Launceston" : -1,
    "Melbourne" : -1,
    "Ararat" : -1,
    "Bairnsdale" : -1,
    "Benalla" : -1,
    "Ballarat" : -1,
    "Bendigo" : -1,
    "Dandenong" : -1,
    "Frankston" : -1,
    "Geelong" : -1,
    "Hamilton" : -1,
    "Horsham" : -1,
    "Latrobe" : -1,
    "Melton" : -1,
    "Mildura" : -1,
    "Sale" : -1,
    "Shepparton" : -1,
    "Swan Hill" : -1,
    "Wangaratta" : -1,
    "Warrnambool" : -1,
    "Wodonga" : -1,
    "Perth" : -1,
    "Albany" : -1,
    "Bunbury" : -1,
    "Busselton" : -1,
    "Fremantle" : -1,
    "Geraldton" : -1,
    "Joondalup" : -1,
    "Kalgoorlie" : -1,
    "Karratha" : -1,
    "Mandurah" : -1,
    "Rockingham" : -1,
    "Sydney" : -1,
    "Albury" : -1,
    "Armidale" : -1,
    "Bathurst" : -1,
    "Blue Mountains" : -1,
    "Broken Hill" : -1,
    "Campbelltown" : -1,
    "Cessnock" : -1,
    "Dubbo" : -1,
    "Goulburn" : -1,
    "Grafton" : -1,
    "Lithgow" : -1,
    "Liverpool" : -1,
    "Newcastle" : -1,
    "Orange" : -1,
    "Parramatta" : -1,
    "Penrith" : -1,
    "Queanbeyan" : -1,
    "Tamworth" : -1,
    "Wagga" : -1,
    "Wollongong" : -1
}
default_city = sorted(default_city.keys())

